"""Phase 7: Add funnel_snapshots, alert_rules, alert_instances, import_logs tables

Revision ID: b0a6f0d6de83
Revises: d5d239dd9f6a
Create Date: 2026-02-24 18:32:50.544027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0a6f0d6de83'
down_revision: Union[str, Sequence[str], None] = 'd5d239dd9f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('notification_channels', sa.JSON(), nullable=False),
    sa.Column('notification_recipients', sa.JSON(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_alert_rules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_index(op.f('ix_alert_rules_tenant_id'), 'alert_rules', ['tenant_id'], unique=False)
    op.create_index('ix_alert_rules_tenant_metric', 'alert_rules', ['tenant_id', 'metric_name'], unique=False)
    op.create_table('funnel_snapshots',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('stage_counts', sa.JSON(), nullable=False),
    sa.Column('new_leads', sa.Integer(), nullable=False),
    sa.Column('new_sms_sent', sa.Integer(), nullable=False),
    sa.Column('new_sms_delivered', sa.Integer(), nullable=False),
    sa.Column('new_calls', sa.Integer(), nullable=False),
    sa.Column('new_answered_calls', sa.Integer(), nullable=False),
    sa.Column('new_successful_calls', sa.Integer(), nullable=False),
    sa.Column('new_invoices', sa.Integer(), nullable=False),
    sa.Column('new_payments', sa.Integer(), nullable=False),
    sa.Column('new_conversions', sa.Integer(), nullable=False),
    sa.Column('daily_revenue', sa.Integer(), nullable=False),
    sa.Column('conversion_rates', sa.JSON(), nullable=False),
    sa.Column('overall_conversion_rate', sa.Float(), nullable=False),
    sa.Column('stage_transitions', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_funnel_snapshots_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funnel_snapshots')),
    sa.UniqueConstraint('tenant_id', 'snapshot_date', name='uq_funnel_snapshot_tenant_date')
    )
    op.create_index('ix_funnel_snapshots_tenant_date', 'funnel_snapshots', ['tenant_id', 'snapshot_date'], unique=False)
    op.create_index(op.f('ix_funnel_snapshots_tenant_id'), 'funnel_snapshots', ['tenant_id'], unique=False)
    op.create_table('import_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('import_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('imported', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('error_details', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_import_logs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_logs'))
    )
    op.create_index(op.f('ix_import_logs_status'), 'import_logs', ['status'], unique=False)
    op.create_index(op.f('ix_import_logs_task_id'), 'import_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_import_logs_tenant_id'), 'import_logs', ['tenant_id'], unique=False)
    op.create_index('ix_import_logs_tenant_status', 'import_logs', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_import_logs_tenant_type', 'import_logs', ['tenant_id', 'import_type'], unique=False)
    op.create_table('alert_instances',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notifications_sent', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('fk_alert_instances_rule_id_alert_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_alert_instances_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_instances'))
    )
    op.create_index(op.f('ix_alert_instances_rule_id'), 'alert_instances', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_instances_status'), 'alert_instances', ['status'], unique=False)
    op.create_index(op.f('ix_alert_instances_tenant_id'), 'alert_instances', ['tenant_id'], unique=False)
    op.create_index('ix_alert_instances_tenant_rule', 'alert_instances', ['tenant_id', 'rule_id'], unique=False)
    op.create_index('ix_alert_instances_tenant_status', 'alert_instances', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_instances_tenant_status', table_name='alert_instances')
    op.drop_index('ix_alert_instances_tenant_rule', table_name='alert_instances')
    op.drop_index(op.f('ix_alert_instances_tenant_id'), table_name='alert_instances')
    op.drop_index(op.f('ix_alert_instances_status'), table_name='alert_instances')
    op.drop_index(op.f('ix_alert_instances_rule_id'), table_name='alert_instances')
    op.drop_table('alert_instances')
    op.drop_index('ix_import_logs_tenant_type', table_name='import_logs')
    op.drop_index('ix_import_logs_tenant_status', table_name='import_logs')
    op.drop_index(op.f('ix_import_logs_tenant_id'), table_name='import_logs')
    op.drop_index(op.f('ix_import_logs_task_id'), table_name='import_logs')
    op.drop_index(op.f('ix_import_logs_status'), table_name='import_logs')
    op.drop_table('import_logs')
    op.drop_index(op.f('ix_funnel_snapshots_tenant_id'), table_name='funnel_snapshots')
    op.drop_index('ix_funnel_snapshots_tenant_date', table_name='funnel_snapshots')
    op.drop_table('funnel_snapshots')
    op.drop_index('ix_alert_rules_tenant_metric', table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_tenant_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
