"""initial_schema

Revision ID: d5d239dd9f6a
Revises: 
Create Date: 2026-02-21 21:24:26.861957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d239dd9f6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_contacts', sa.Integer(), nullable=False),
    sa.Column('max_sms_per_month', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('current_contacts', sa.Integer(), nullable=False),
    sa.Column('current_month_sms', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('data_source_connections',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('connection_config', sa.JSON(), nullable=False),
    sa.Column('field_mappings', sa.JSON(), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=50), nullable=True),
    sa.Column('last_sync_records', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_data_source_connections_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_source_connections'))
    )
    op.create_index(op.f('ix_data_source_connections_tenant_id'), 'data_source_connections', ['tenant_id'], unique=False)
    op.create_table('lead_categories',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['lead_categories.id'], name=op.f('fk_lead_categories_parent_id_lead_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_lead_categories_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_categories'))
    )
    op.create_index(op.f('ix_lead_categories_tenant_id'), 'lead_categories', ['tenant_id'], unique=False)
    op.create_index('ix_lead_categories_tenant_name', 'lead_categories', ['tenant_id', 'name'], unique=False)
    op.create_table('products',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('current_price', sa.Integer(), nullable=False),
    sa.Column('min_order_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('target_segments', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_products_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=False)
    op.create_index('ix_products_tenant_category', 'products', ['tenant_id', 'category'], unique=False)
    op.create_index('ix_products_tenant_code', 'products', ['tenant_id', 'code'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('salespersons',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_leads_assigned', sa.Integer(), nullable=False),
    sa.Column('total_conversions', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_salespersons_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salespersons'))
    )
    op.create_index(op.f('ix_salespersons_tenant_id'), 'salespersons', ['tenant_id'], unique=False)
    op.create_table('sms_templates',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('target_segments', sa.JSON(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('total_delivered', sa.Integer(), nullable=False),
    sa.Column('total_conversions', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sms_templates_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_templates'))
    )
    op.create_index(op.f('ix_sms_templates_tenant_id'), 'sms_templates', ['tenant_id'], unique=False)
    op.create_index('ix_sms_templates_tenant_name', 'sms_templates', ['tenant_id', 'name'], unique=False)
    op.create_table('tenant_users',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_users'))
    )
    op.create_index(op.f('ix_tenant_users_email'), 'tenant_users', ['email'], unique=False)
    op.create_index(op.f('ix_tenant_users_tenant_id'), 'tenant_users', ['tenant_id'], unique=False)
    op.create_table('contacts',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('stage_entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rfm_segment', sa.String(length=50), nullable=True),
    sa.Column('rfm_score', sa.String(length=3), nullable=True),
    sa.Column('recency_score', sa.Integer(), nullable=True),
    sa.Column('frequency_score', sa.Integer(), nullable=True),
    sa.Column('monetary_score', sa.Integer(), nullable=True),
    sa.Column('last_rfm_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_sms_sent', sa.Integer(), nullable=False),
    sa.Column('total_sms_delivered', sa.Integer(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('total_answered_calls', sa.Integer(), nullable=False),
    sa.Column('total_call_duration', sa.Integer(), nullable=False),
    sa.Column('total_invoices', sa.Integer(), nullable=False),
    sa.Column('total_paid_invoices', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Integer(), nullable=False),
    sa.Column('last_purchase_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_purchase_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('custom_fields', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['lead_categories.id'], name=op.f('fk_contacts_category_id_lead_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_contacts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index(op.f('ix_contacts_current_stage'), 'contacts', ['current_stage'], unique=False)
    op.create_index(op.f('ix_contacts_phone_number'), 'contacts', ['phone_number'], unique=False)
    op.create_index(op.f('ix_contacts_rfm_segment'), 'contacts', ['rfm_segment'], unique=False)
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_index('ix_contacts_tenant_phone', 'contacts', ['tenant_id', 'phone_number'], unique=True)
    op.create_index('ix_contacts_tenant_segment', 'contacts', ['tenant_id', 'rfm_segment'], unique=False)
    op.create_index('ix_contacts_tenant_stage', 'contacts', ['tenant_id', 'current_stage'], unique=False)
    op.create_table('lead_sources',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_import_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_leads', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['lead_categories.id'], name=op.f('fk_lead_sources_category_id_lead_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_lead_sources_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_sources'))
    )
    op.create_index(op.f('ix_lead_sources_tenant_id'), 'lead_sources', ['tenant_id'], unique=False)
    op.create_table('product_prices',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_prices_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_prices'))
    )
    op.create_index('ix_product_prices_product_effective', 'product_prices', ['product_id', 'effective_from'], unique=False)
    op.create_index(op.f('ix_product_prices_product_id'), 'product_prices', ['product_id'], unique=False)
    op.create_table('call_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('call_type', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('salesperson_id', sa.UUID(), nullable=True),
    sa.Column('salesperson_name', sa.String(length=255), nullable=True),
    sa.Column('salesperson_phone', sa.String(length=20), nullable=True),
    sa.Column('call_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('call_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_successful', sa.Boolean(), nullable=False),
    sa.Column('voip_call_id', sa.String(length=100), nullable=True),
    sa.Column('voip_channel', sa.String(length=100), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_call_logs_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['salesperson_id'], ['salespersons.id'], name=op.f('fk_call_logs_salesperson_id_salespersons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_call_logs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_logs'))
    )
    op.create_index(op.f('ix_call_logs_contact_id'), 'call_logs', ['contact_id'], unique=False)
    op.create_index(op.f('ix_call_logs_phone_number'), 'call_logs', ['phone_number'], unique=False)
    op.create_index(op.f('ix_call_logs_status'), 'call_logs', ['status'], unique=False)
    op.create_index('ix_call_logs_tenant_call_start', 'call_logs', ['tenant_id', 'call_start'], unique=False)
    op.create_index(op.f('ix_call_logs_tenant_id'), 'call_logs', ['tenant_id'], unique=False)
    op.create_index('ix_call_logs_tenant_phone', 'call_logs', ['tenant_id', 'phone_number'], unique=False)
    op.create_index('ix_call_logs_tenant_salesperson', 'call_logs', ['tenant_id', 'salesperson_id'], unique=False)
    op.create_index('ix_call_logs_tenant_status', 'call_logs', ['tenant_id', 'status'], unique=False)
    op.create_table('invoices',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_type', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('tax_amount', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('salesperson_id', sa.UUID(), nullable=True),
    sa.Column('salesperson_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_invoices_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['salesperson_id'], ['salespersons.id'], name=op.f('fk_invoices_salesperson_id_salespersons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_invoices_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_index(op.f('ix_invoices_contact_id'), 'invoices', ['contact_id'], unique=False)
    op.create_index('ix_invoices_external_id', 'invoices', ['tenant_id', 'external_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_phone_number'), 'invoices', ['phone_number'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_index('ix_invoices_tenant_issued', 'invoices', ['tenant_id', 'issued_at'], unique=False)
    op.create_index('ix_invoices_tenant_phone', 'invoices', ['tenant_id', 'phone_number'], unique=False)
    op.create_index('ix_invoices_tenant_status', 'invoices', ['tenant_id', 'status'], unique=False)
    op.create_table('sms_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('template_name', sa.String(length=255), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('sender_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('status_message', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_sms_logs_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sms_logs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_logs'))
    )
    op.create_index(op.f('ix_sms_logs_contact_id'), 'sms_logs', ['contact_id'], unique=False)
    op.create_index(op.f('ix_sms_logs_phone_number'), 'sms_logs', ['phone_number'], unique=False)
    op.create_index(op.f('ix_sms_logs_status'), 'sms_logs', ['status'], unique=False)
    op.create_index(op.f('ix_sms_logs_tenant_id'), 'sms_logs', ['tenant_id'], unique=False)
    op.create_index('ix_sms_logs_tenant_phone', 'sms_logs', ['tenant_id', 'phone_number'], unique=False)
    op.create_index('ix_sms_logs_tenant_sent_at', 'sms_logs', ['tenant_id', 'sent_at'], unique=False)
    op.create_index('ix_sms_logs_tenant_status', 'sms_logs', ['tenant_id', 'status'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_line_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_invoice_line_items_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_line_items'))
    )
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_payments_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_payments_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_contact_id'), 'payments', ['contact_id'], unique=False)
    op.create_index('ix_payments_external_id', 'payments', ['tenant_id', 'external_id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_phone_number'), 'payments', ['phone_number'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_index('ix_payments_tenant_paid_at', 'payments', ['tenant_id', 'paid_at'], unique=False)
    op.create_index('ix_payments_tenant_phone', 'payments', ['tenant_id', 'phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_tenant_phone', table_name='payments')
    op.drop_index('ix_payments_tenant_paid_at', table_name='payments')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_phone_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index('ix_payments_external_id', table_name='payments')
    op.drop_index(op.f('ix_payments_contact_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index('ix_sms_logs_tenant_status', table_name='sms_logs')
    op.drop_index('ix_sms_logs_tenant_sent_at', table_name='sms_logs')
    op.drop_index('ix_sms_logs_tenant_phone', table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_tenant_id'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_status'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_phone_number'), table_name='sms_logs')
    op.drop_index(op.f('ix_sms_logs_contact_id'), table_name='sms_logs')
    op.drop_table('sms_logs')
    op.drop_index('ix_invoices_tenant_status', table_name='invoices')
    op.drop_index('ix_invoices_tenant_phone', table_name='invoices')
    op.drop_index('ix_invoices_tenant_issued', table_name='invoices')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_phone_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index('ix_invoices_external_id', table_name='invoices')
    op.drop_index(op.f('ix_invoices_contact_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_call_logs_tenant_status', table_name='call_logs')
    op.drop_index('ix_call_logs_tenant_salesperson', table_name='call_logs')
    op.drop_index('ix_call_logs_tenant_phone', table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_tenant_id'), table_name='call_logs')
    op.drop_index('ix_call_logs_tenant_call_start', table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_status'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_phone_number'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_contact_id'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_index(op.f('ix_product_prices_product_id'), table_name='product_prices')
    op.drop_index('ix_product_prices_product_effective', table_name='product_prices')
    op.drop_table('product_prices')
    op.drop_index(op.f('ix_lead_sources_tenant_id'), table_name='lead_sources')
    op.drop_table('lead_sources')
    op.drop_index('ix_contacts_tenant_stage', table_name='contacts')
    op.drop_index('ix_contacts_tenant_segment', table_name='contacts')
    op.drop_index('ix_contacts_tenant_phone', table_name='contacts')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_rfm_segment'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_phone_number'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_current_stage'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_tenant_users_tenant_id'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_email'), table_name='tenant_users')
    op.drop_table('tenant_users')
    op.drop_index('ix_sms_templates_tenant_name', table_name='sms_templates')
    op.drop_index(op.f('ix_sms_templates_tenant_id'), table_name='sms_templates')
    op.drop_table('sms_templates')
    op.drop_index(op.f('ix_salespersons_tenant_id'), table_name='salespersons')
    op.drop_table('salespersons')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index('ix_products_tenant_code', table_name='products')
    op.drop_index('ix_products_tenant_category', table_name='products')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_lead_categories_tenant_name', table_name='lead_categories')
    op.drop_index(op.f('ix_lead_categories_tenant_id'), table_name='lead_categories')
    op.drop_table('lead_categories')
    op.drop_index(op.f('ix_data_source_connections_tenant_id'), table_name='data_source_connections')
    op.drop_table('data_source_connections')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
