"""
Core Domain Module
Exports all core domain components
"""

from .entities import (
    AggregateRoot,
    DateRange,
    DomainEvent,
    Entity,
    Money,
    Percentage,
    PhoneNumber,
    TenantAggregateRoot,
    TenantEntity,
    ValueObject,
)
from .enums import (
    AlertSeverity,
    AlertType,
    CallSource,
    CallType,
    CampaignStatus,
    DataSourceType,
    ETLJobStatus,
    FunnelStage,
    InvoiceStatus,
    LeadSource,
    PaymentStatus,
    RFMSegment,
    SMSDirection,
    SMSStatus,
)
from .events import (
    AlertTriggeredEvent,
    CallAnsweredEvent,
    CallReceivedEvent,
    CampaignCompletedEvent,
    CampaignCreatedEvent,
    CampaignStartedEvent,
    ContactSegmentChangedEvent,
    ConversionEvent,
    DataImportCompletedEvent,
    FunnelStageProgressedEvent,
    InvoiceCancelledEvent,
    InvoiceCreatedEvent,
    InvoicePaidEvent,
    LeadAssignedEvent,
    LeadCategorizedEvent,
    LeadCreatedEvent,
    SegmentRecommendationEvent,
    SMSDeliveredEvent,
    SMSFailedEvent,
    SMSSentEvent,
)

__all__ = [
    # Base classes
    "ValueObject",
    "Entity",
    "AggregateRoot",
    "DomainEvent",
    "TenantEntity",
    "TenantAggregateRoot",
    # Value Objects
    "PhoneNumber",
    "Money",
    "DateRange",
    "Percentage",
    # Enums
    "FunnelStage",
    "CallType",
    "CallSource",
    "SMSStatus",
    "SMSDirection",
    "InvoiceStatus",
    "PaymentStatus",
    "RFMSegment",
    "LeadSource",
    "CampaignStatus",
    "AlertSeverity",
    "AlertType",
    "DataSourceType",
    "ETLJobStatus",
    # Events
    "LeadCreatedEvent",
    "LeadCategorizedEvent",
    "LeadAssignedEvent",
    "SMSSentEvent",
    "SMSDeliveredEvent",
    "SMSFailedEvent",
    "CallReceivedEvent",
    "CallAnsweredEvent",
    "InvoiceCreatedEvent",
    "InvoicePaidEvent",
    "InvoiceCancelledEvent",
    "ContactSegmentChangedEvent",
    "SegmentRecommendationEvent",
    "CampaignCreatedEvent",
    "CampaignStartedEvent",
    "CampaignCompletedEvent",
    "FunnelStageProgressedEvent",
    "ConversionEvent",
    "DataImportCompletedEvent",
    "AlertTriggeredEvent",
]

